#!!!WIP Do not use yet!!!

name: C++ Compile and Release

on:
  workflow_dispatch:

jobs:
  BuildLib:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build with Makefile
        run: make

      - name: Archive the built file
        run: |
          mkdir -p release
          cp output_file release/
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-binary
          path: release/output_file

  Release:
    needs: BuildLib
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: compiled-binary
          path: release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/output_file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
